#!/usr/bin/env python3
# SPDX-License-Identifier: CC0-1.0
# Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
# a separate, commercially licensed product and is not covered by CC0.
# =============================================================================
# BACnet Profile Example - B-SS (BACnet Smart Sensor) - Python
#
# This example shows the *minimum* needed to implement the BACnet "B-SS"
# (Smart Sensor) device profile with the CAS BACnet Stack.
#
# A B-SS is "a simple sensing device with very limited resources" (ANSI/ASHRAE
# 135, Annex L.4.5). Its only mandatory capability is:
#
#     DS-RP-B  - respond to ReadProperty requests
#
# plus the ability to be discovered: it answers Who-Is with I-Am (handled
# automatically by the stack) and announces itself with an unsolicited I-Am on
# start-up.
#
# A B-SS does NOT require WriteProperty, COV, alarms/events, scheduling, or
# trending - so this example deliberately does NOT enable any of those. That is
# the whole point of a profile example: implement exactly what the profile
# asks for, nothing more.
#
# This is the Python edition of BACnetProfileExample-B-SS-CPP / -CS - same
# objects, same names, same section layout, so you can diff the three side by
# side. The systematic difference here is the binding mechanism: Python talks
# to the native CAS BACnet Stack library through `ctypes` (the vendored
# adapter in cas_bacnet_stack/), which means:
#
#   - an EXPLICIT load step, like the C++ edition: `ctypes.CDLL(libname)` then
#     `bacnet.bind(library)`, both before any BACnetStack_* call (see "Load
#     the CAS BACnet Stack" below) - unlike the C# edition, where the .NET
#     runtime resolves the native library implicitly on first P/Invoke call.
#   - every Get*Property callback is a plain Python function wrapped in a
#     ctypes.CFUNCTYPE, receiving ctypes POINTER out-parameters it indexes
#     like a list (`value[0] = 21.5`) instead of C#'s raw pointers or a
#     managed-buffer marshaling layer.
#   - THE STACK IS SINGLE-THREADED BY CONTRACT. Nothing in this file spawns a
#     thread that touches the stack; all networking is done through a
#     non-blocking socket (common/simple_udp.py) polled once per
#     BACnetStack_Tick() in the same loop - see "Run the stack" at the bottom.
#
# The device exposes three read-only sensor objects plus the Network Port
# object that every BACnet device must have. Each object is given a colour name
# (a convention shared across this example series):
#
#     Device 389001          "Rainbow"    (instance configurable with --deviceID)
#     Analog Input  1        "Bronze"     (REAL, degrees Celsius; starts at 21.5)
#     Binary Input  1        "Emerald"    (active / inactive)
#     Multi-State Input 1    "Hot Pink"   (an enumerated state, 1..3)
#     Network Port 1         "Vermilion"  (the BACnet/IP port - required)
#
# To be a conformant BACnet device (Protocol_Revision 24) each object must
# expose its full set of REQUIRED properties. Most are generated by the stack
# (Object_Identifier, Object_Type, Status_Flags, Object_List, Protocol_*).
# Event_State is NOT generated - with no alarming configured it simply reads its
# datatype default of normal(0), correct by coincidence, not because the stack
# computes it. The handful that the application must supply are served by the
# Get*Property callbacks below, and a few are turned on with SetPropertyEnabled.
#
# Interactive keys (handled at the bottom of this file): h = help, q = quit,
# up/down = nudge Analog Input 1 by +/-1.1 - only when stdin is a real,
# non-redirected console (see "Interactive keys" below). Command line:
# --port <n>, --deviceID <n>.
#
# All the UDP/stack plumbing lives in common/ so this file can stay focused on
# the BACnet logic.
# =============================================================================

import ctypes
import os
import signal
import sys
import time
from argparse import ArgumentParser

# Make `cas_bacnet_stack` and `common` importable regardless of the caller's
# working directory - this example is run as `python3 main.py`, not
# `python3 -m ...`, so the script's own directory must be on sys.path.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Show printf-equivalent output immediately, even when stdout is redirected to
# a file/pipe (a background run, a CI smoke test): Python fully buffers stdout
# when it is not a terminal, so without this the "ready" banner would not
# actually reach the file until the process exits or the buffer fills - the
# C++ edition's setvbuf(stdout, NULL, _IONBF, 0) does the same job.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)

from cas_bacnet_stack.CASBACnetStackAdapter import libname
import cas_bacnet_stack.CASBACnetStackAdapterBindings as bacnet
from common.simple_udp import SimpleUDP
from common import cas_example_helper
from common import cas_bacnet_stack_example_constants as c

# -----------------------------------------------------------------------------
# 1. Example + device configuration
# -----------------------------------------------------------------------------
APP_NAME = "BACnet B-SS (Smart Sensor) Example - Python"
APP_VERSION = "1.0.0"

# The device instance. BACnet requires this to be configurable, so it defaults
# to 389001 and can be overridden on the command line with --deviceID. Keep it
# configurable in your product: it must be unique across the internetwork.
g_device_instance = 389001

# ---- Device identity: CHANGE ALL OF THIS BEFORE YOU SHIP --------------------
# Everything in this block is read by clients and shown to the operator in
# every discovery tool on the network. Left as-is, your product will appear on
# a real site announcing itself as a Chipkin demo. None of it is cosmetic:
# Object_Name must be unique across the BACnet internetwork, and Model_Name /
# Vendor_Identifier are what a building operator uses to identify your device.
#
# This block is the ship checklist. Every constant below has a note saying
# what to change it to; nothing here is safe to leave at its example value.
# -----------------------------------------------------------------------------

# Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
# to YOUR company's vendor ID before shipping a product. Vendor IDs are
# assigned by ASHRAE - request one (free) at
# https://bacnet.org/assigned-vendor-ids/. Update VENDOR_NAME below to match.
VENDOR_IDENTIFIER = 389

# The Device object's Object_Name.
#
# THIS IS THE ONE THAT WILL BITE YOU. Object_Name must be unique across the
# whole BACnet internetwork, and here it is a COMPILE-TIME (well, module-load-
# time) constant. The device instance is runtime-configurable via --deviceID,
# so it is easy to ship two units, configure their instances correctly, and
# still have BOTH announce Object_Name "Rainbow" - a spec violation, and a hard
# BTL failure. In a real product Object_Name must be per-unit configurable
# too: derive it from a serial number, DIP switches, a config file, or add a
# --deviceName argument.
DEVICE_NAME = "Rainbow"

# The Device object's Description. Change it to what YOUR device actually is;
# this string describes this tutorial.
DEVICE_DESCRIPTION = (
    "Chipkin CAS BACnet Stack example - B-SS (Smart Sensor) profile. "
    "Demonstrates DS-RP-B: ReadProperty plus Who-Is/I-Am with read-only sensor objects."
)

# Device identity strings (read by clients, and used to populate I-Am).
#   VENDOR_NAME - your company name; it must match VENDOR_IDENTIFIER above.
#   MODEL_NAME  - your model designation. This is what a building operator
#                 reads to identify your device in a discovery tool.
#   FIRMWARE_REVISION / APPLICATION_SOFTWARE_VERSION - your real versions.
#                 Wire them to your build rather than hard-coding a number
#                 that will go stale.
VENDOR_NAME = "Chipkin Automation Systems"
MODEL_NAME = "CAS BACnet Stack Example - B-SS"
FIRMWARE_REVISION = "1.0.0"
APPLICATION_SOFTWARE_VERSION = "1.0.0"

# The sensor objects (all instance 1) and their colour names.
ANALOG_INPUT_INSTANCE = 1       # "Bronze"
BINARY_INPUT_INSTANCE = 1       # "Emerald"
MULTI_STATE_INPUT_INSTANCE = 1  # "Hot Pink"
MULTI_STATE_INPUT_NUMBER_OF_STATES = 3
MULTI_STATE_TEXT = ("On", "Off", "Auto")

# The Network Port object - every BACnet device must have one. It represents
# the BACnet/IP port this device communicates on.
NETWORK_PORT_INSTANCE = 1  # "Vermilion"
MAX_APDU_LENGTH = 1476     # BACnet/IP APDU length

# BACnet/IP addressing the Network Port reports. The IP address and subnet
# mask are filled in at start-up from the host's primary interface; the
# gateway is left unset (0.0.0.0) for this example. The stack also uses
# IP_Address + BACnet_IP_UDP_Port to build the port's MAC_Address
# automatically.
g_ip_address = [0, 0, 0, 0]
g_ip_subnet_mask = [0, 0, 0, 0]
g_ip_default_gateway = [0, 0, 0, 0]
g_bacnet_ip_udp_port = 47808

# Analog Input 1's live present value (degrees Celsius). Starts at 21.5 and is
# nudged by the up/down arrow keys. A real sensor would update this from
# hardware instead.
g_analog_input_1_value = 21.5

udp = SimpleUDP()

# -----------------------------------------------------------------------------
# 2. Property "get" callbacks
#
# The stack calls these when a client reads a property. For each data type the
# stack uses a separate callback. We return True (and fill the out-param) when
# we recognise the (object, property) pair, and False otherwise.
#
# THE errorCode OUT-PARAMETER. Every Get callback ends with a trailing
# errorCode pointer. The stack PRESETS it to success (84) before the call, and
# reads it only if you return False. That gives a declining callback two
# distinct meanings:
#
#   1. return False and LEAVE errorCode ALONE -> "I have no opinion on this
#      property." The stack falls back to its own handling (see below).
#   2. return False and SET errorCode[0]      -> "This read fails, with THIS
#      BACnet error." The client gets exactly that Error-PDU.
#
# Option 2 is new (CAS BACnet Stack issue #974); before it, a Get callback had
# no way to name an error at all. Do not reach for it reflexively - option 1 is
# still the right answer most of the time, for the reason in the next
# paragraph.
#
# WHAT False-WITHOUT-AN-ERROR-CODE ACTUALLY DOES - the most important
# paragraph in this file, and the opposite of what most people assume. It
# does NOT reliably produce a BACnet error. The stack errors only for the
# handful of properties it refuses to invent: Present_Value,
# Number_Of_States, Relinquish_Default, Local_Date, Local_Time, and a Network
# Port's APDU_Length (declining one of those now reads back as Error:
# read-access-denied, where older stack versions said value-not-initialized).
# For EVERYTHING ELSE, a False return means the stack SILENTLY SUBSTITUTES a
# default:
#     Object_Name -> the literal string "undefined"
#     Units       -> no-units (95)
#     otherwise   -> a datatype zero-value
#
# AND THAT FALLBACK IS LORE-BEARING, WHICH IS WHY WE DO NOT "FIX" IT HERE. It
# is tempting to end every callback with errorCode[0] = unknown-property so
# nothing is ever silently invented. That breaks the device. The stack relies
# on the decline-and-fabricate path to answer required properties the
# application is not expected to serve - the Device's
# Max_APDU_Length_Accepted, APDU_Timeout and Number_Of_APDU_Retries among
# them. Name an error on the catch-all return and those required properties
# start failing instead of answering. So: set errorCode[0] ONLY where THIS
# device knows the read is wrong. There is exactly one such case below
# (State_Text with an out-of-range array index); the catch-all `return False`
# at the end of each callback deliberately leaves errorCode alone.
#
# ADDING AN OBJECT? READ THIS FIRST.
# The consequence is the opposite of reassuring. These callbacks are not
# uniformly strict:
#   - get_property_real / get_property_enumerated /
#     get_property_unsigned_integer match on object type AND INSTANCE (e.g.
#     object_instance == ANALOG_INPUT_INSTANCE). A new instance falls through
#     every one of those checks.
#   - get_property_bool matches on TYPE ONLY, so a new instance gets
#     Out_Of_Service for free.
# So a half-added object does NOT fail loudly. Its Present_Value errors (that
# one is in the list above) - but its Object_Name reads back as "undefined"
# and its Units as no-units, with no error at all. Add two objects that way
# and BOTH report Object_Name "undefined": duplicate object names within one
# device, which is a spec violation and a hard BTL failure, and which every
# scan tool will show you as a healthy object. The device looks fine and is
# non-conformant.
#
# So: when you add an instance, walk EVERY callback below, then read back
# every required property of the new object and DIFF IT against the existing
# one. Do not trust "it scanned OK" - that is exactly the failure mode. See
# TUTORIAL.md "Add a second analog input" for the edits.
# -----------------------------------------------------------------------------


# REAL (floating point) - the Analog Input's Present_Value.
def get_property_real(device_instance, object_type, object_instance, property_identifier,
                       value, use_array_index, property_array_index, error_code):
    if (device_instance == g_device_instance and
            object_type == c.OBJECT_TYPE_ANALOG_INPUT and
            object_instance == ANALOG_INPUT_INSTANCE and
            property_identifier == c.PROPERTY_IDENTIFIER_PRESENT_VALUE):
        # ON REAL HARDWARE: return the live sensor reading here. Read it from a
        # cached variable that your hardware updates (as g_analog_input_1_value
        # is), NOT directly from a slow/blocking device (I2C, SPI, ADC
        # conversion): this callback runs on the BACnetStack_Tick() call, so
        # blocking it delays all BACnet processing. Sample the sensor on a
        # timer/another thread and just hand back the latest value from here.
        value[0] = g_analog_input_1_value
        return True
    return False


# ENUMERATED - the Binary Input's Present_Value (0 = inactive, 1 = active),
# the Analog Input's Units, and the Network Port's BACnet_IP_Mode.
def get_property_enumerated(device_instance, object_type, object_instance, property_identifier,
                             value, use_array_index, property_array_index, error_code):
    if device_instance != g_device_instance:
        return False
    if object_type == c.OBJECT_TYPE_BINARY_INPUT and object_instance == BINARY_INPUT_INSTANCE:
        if property_identifier == c.PROPERTY_IDENTIFIER_PRESENT_VALUE:
            # ON REAL HARDWARE: return your cached input state here - the same
            # rule as get_property_real above applies (never block this
            # callback on slow I/O).
            value[0] = 0  # inactive - the series-wide starting value
            return True
        if property_identifier == c.PROPERTY_IDENTIFIER_POLARITY:
            value[0] = c.POLARITY_NORMAL  # required property of a Binary Input
            return True
    if (object_type == c.OBJECT_TYPE_ANALOG_INPUT and object_instance == ANALOG_INPUT_INSTANCE and
            property_identifier == c.PROPERTY_IDENTIFIER_UNITS):
        value[0] = c.ENGINEERING_UNITS_DEGREES_CELSIUS
        return True
    if (object_type == c.OBJECT_TYPE_NETWORK_PORT and object_instance == NETWORK_PORT_INSTANCE and
            property_identifier == c.PROPERTY_IDENTIFIER_BACNET_IP_MODE):
        value[0] = c.BACNET_IP_MODE_NORMAL  # not foreign-device, not BBMD
        return True
    return False


# UNSIGNED INTEGER - the Multi-State Input's Present_Value, and the Device's
# Vendor_Identifier (the stack also uses Vendor_Identifier to build I-Am).
def get_property_unsigned_integer(device_instance, object_type, object_instance, property_identifier,
                                   value, use_array_index, property_array_index, error_code):
    if device_instance != g_device_instance:
        return False
    if object_type == c.OBJECT_TYPE_MULTI_STATE_INPUT and object_instance == MULTI_STATE_INPUT_INSTANCE:
        if property_identifier == c.PROPERTY_IDENTIFIER_PRESENT_VALUE:
            value[0] = 1  # state 1 (valid range is 1..Number_Of_States)
            return True
        if property_identifier == c.PROPERTY_IDENTIFIER_NUMBER_OF_STATES:
            value[0] = MULTI_STATE_INPUT_NUMBER_OF_STATES  # required property
            return True
        # State_Text is an array. The stack asks for its LENGTH here (array
        # index 0) before reading each element via get_property_character_string.
        if (property_identifier == c.PROPERTY_IDENTIFIER_STATE_TEXT and
                use_array_index and property_array_index == 0):
            value[0] = MULTI_STATE_INPUT_NUMBER_OF_STATES
            return True
    if (object_type == c.OBJECT_TYPE_DEVICE and object_instance == g_device_instance and
            property_identifier == c.PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER):
        value[0] = VENDOR_IDENTIFIER
        return True
    if object_type == c.OBJECT_TYPE_NETWORK_PORT and object_instance == NETWORK_PORT_INSTANCE:
        if property_identifier == c.PROPERTY_IDENTIFIER_APDU_LENGTH:
            value[0] = MAX_APDU_LENGTH
            return True
        if property_identifier == c.PROPERTY_IDENTIFIER_REFERENCE_PORT:
            value[0] = c.NETWORK_PORT_REFERENCE_PORT_NONE
            return True
        if property_identifier == c.PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT:
            value[0] = g_bacnet_ip_udp_port
            return True
    return False


# BOOLEAN - Out_Of_Service is a required property of every input object and of
# the Network Port. This is a read-only sensor, so nothing is ever out of
# service: always False.
def get_property_bool(device_instance, object_type, object_instance, property_identifier,
                       value, use_array_index, property_array_index, error_code):
    if device_instance != g_device_instance:
        return False
    if property_identifier == c.PROPERTY_IDENTIFIER_OUT_OF_SERVICE and object_type in (
            c.OBJECT_TYPE_ANALOG_INPUT, c.OBJECT_TYPE_BINARY_INPUT,
            c.OBJECT_TYPE_MULTI_STATE_INPUT, c.OBJECT_TYPE_NETWORK_PORT):
        value[0] = False
        return True
    return False


# OCTET STRING - the Network Port's BACnet/IP addressing. The stack cannot
# know the host's IP, so the application must supply IP_Address and
# IP_Subnet_Mask (and IP_Default_Gateway). Each is four octets. The stack also
# reads IP_Address (with BACnet_IP_UDP_Port) to build the port's six-octet
# MAC_Address.
def get_property_octet_string(device_instance, object_type, object_instance, property_identifier,
                               value, value_element_count, max_element_count,
                               use_array_index, property_array_index, error_code):
    if (device_instance != g_device_instance or
            object_type != c.OBJECT_TYPE_NETWORK_PORT or
            object_instance != NETWORK_PORT_INSTANCE or
            max_element_count < 4):
        return False
    if property_identifier == c.PROPERTY_IDENTIFIER_IP_ADDRESS:
        source = g_ip_address
    elif property_identifier == c.PROPERTY_IDENTIFIER_IP_SUBNET_MASK:
        source = g_ip_subnet_mask
    elif property_identifier == c.PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY:
        source = g_ip_default_gateway
    else:
        return False
    for i in range(4):
        value[i] = source[i]
    value_element_count[0] = 4
    return True


# Small helper: copy a Python str into the stack's character-string buffer as
# UTF-8 and set the element count + encoding. Returns True (so callers can
# `return`).
def _return_character_string(text, value, value_element_count, max_element_count, encoding_type):
    encoded = text.encode("utf-8")
    length = len(encoded)
    if length > max_element_count:
        # Truncate SILENTLY to fit the stack's buffer. max_element_count is
        # MAX_CHARACTER_STRING_SIZE (256 in this build), and our longest
        # string (DEVICE_DESCRIPTION) fits with room to spare - so this never
        # trips here. But if you build with a smaller embedded buffer, that
        # limit drops, and a long Object_Name or Description would be clipped
        # mid-word with nothing on the wire or console to tell you. If you
        # lengthen any served string, check it against
        # MAX_CHARACTER_STRING_SIZE for your target, or make this truncation
        # loud.
        length = max_element_count
        encoded = encoded[:length]
    for i in range(length):
        value[i] = encoded[i]
    value_element_count[0] = length
    encoding_type[0] = c.CHARACTER_STRING_ENCODING_UTF8
    return True


# CHARACTER STRING - Object_Name for each object, and the device Description.
def get_property_character_string(device_instance, object_type, object_instance, property_identifier,
                                   value, value_element_count, max_element_count, encoding_type,
                                   use_array_index, property_array_index, error_code):
    if device_instance != g_device_instance:
        return False

    # State_Text (optional) - one label per state of the Multi-State Input. It
    # is a BACnet array, so the stack asks for one element at a time by index
    # (1..Number_Of_States). Present_Value 1 -> "On", 2 -> "Off", 3 -> "Auto".
    if (object_type == c.OBJECT_TYPE_MULTI_STATE_INPUT and
            object_instance == MULTI_STATE_INPUT_INSTANCE and
            property_identifier == c.PROPERTY_IDENTIFIER_STATE_TEXT and use_array_index):
        if 1 <= property_array_index <= MULTI_STATE_INPUT_NUMBER_OF_STATES:
            return _return_character_string(MULTI_STATE_TEXT[property_array_index - 1],
                                             value, value_element_count, max_element_count,
                                             encoding_type)
        # The one place in this file where naming an error is clearly right:
        # the client asked for State_Text[n] and this object has no element
        # n. That is not "no opinion" - it is a wrong read, and the spec has
        # a code for it. Without this the client would silently receive an
        # empty string.
        error_code[0] = c.ERROR_CODE_INVALID_ARRAY_INDEX
        return False

    # Object_Name - the colour name for each object.
    if property_identifier == c.PROPERTY_IDENTIFIER_OBJECT_NAME:
        if object_type == c.OBJECT_TYPE_DEVICE and object_instance == g_device_instance:
            return _return_character_string(DEVICE_NAME, value, value_element_count,
                                             max_element_count, encoding_type)
        if object_type == c.OBJECT_TYPE_ANALOG_INPUT and object_instance == ANALOG_INPUT_INSTANCE:
            return _return_character_string("Bronze", value, value_element_count,
                                             max_element_count, encoding_type)
        if object_type == c.OBJECT_TYPE_BINARY_INPUT and object_instance == BINARY_INPUT_INSTANCE:
            return _return_character_string("Emerald", value, value_element_count,
                                             max_element_count, encoding_type)
        if object_type == c.OBJECT_TYPE_MULTI_STATE_INPUT and object_instance == MULTI_STATE_INPUT_INSTANCE:
            return _return_character_string("Hot Pink", value, value_element_count,
                                             max_element_count, encoding_type)
        if object_type == c.OBJECT_TYPE_NETWORK_PORT and object_instance == NETWORK_PORT_INSTANCE:
            return _return_character_string("Vermilion", value, value_element_count,
                                             max_element_count, encoding_type)

    # The remaining strings are all on the Device object - its identity, read
    # by clients and used to populate the device's I-Am / object list.
    if object_type == c.OBJECT_TYPE_DEVICE and object_instance == g_device_instance:
        if property_identifier == c.PROPERTY_IDENTIFIER_DESCRIPTION:
            return _return_character_string(DEVICE_DESCRIPTION, value, value_element_count,
                                             max_element_count, encoding_type)
        if property_identifier == c.PROPERTY_IDENTIFIER_VENDOR_NAME:
            return _return_character_string(VENDOR_NAME, value, value_element_count,
                                             max_element_count, encoding_type)
        if property_identifier == c.PROPERTY_IDENTIFIER_MODEL_NAME:
            return _return_character_string(MODEL_NAME, value, value_element_count,
                                             max_element_count, encoding_type)
        if property_identifier == c.PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
            return _return_character_string(FIRMWARE_REVISION, value, value_element_count,
                                             max_element_count, encoding_type)
        if property_identifier == c.PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
            return _return_character_string(APPLICATION_SOFTWARE_VERSION, value, value_element_count,
                                             max_element_count, encoding_type)

    return False


# -----------------------------------------------------------------------------
# 3. Interactive keys (a simplification - see TUTORIAL.md)
# -----------------------------------------------------------------------------
# The C++ edition polls raw console keys (including arrow-key escape
# sequences) every millisecond in its own loop. The C# edition uses .NET's
# built-in non-blocking Console.KeyAvailable/ReadKey. Python has no single
# stdlib mechanism that works the same way on both platforms, so this file
# picks the platform-appropriate one: `msvcrt` on Windows (a simple
# kbhit()/getch() poll), `termios`/`tty`/`select` on POSIX (put the terminal
# into cbreak mode and poll with a zero-timeout select()). Both are skipped
# entirely when stdin is not a real, non-redirected console (a background
# process, a CI smoke test, output piped to a file) - the device still runs
# (BACnetStack_Tick() keeps ticking, and Ctrl+C still works via the SIGINT
# handler below), it just cannot be nudged from the keyboard. This mirrors
# the C# edition's Console.IsInputRedirected check.
# -----------------------------------------------------------------------------

_interactive = sys.stdin.isatty()

if _interactive and os.name == "nt":
    import msvcrt

    def _restore_input():
        pass  # msvcrt needs no mode restoration

    def _poll_key():
        if not msvcrt.kbhit():
            return None
        ch = msvcrt.getch()
        if ch in (b"\x00", b"\xe0"):  # arrow-key prefix on Windows
            ch2 = msvcrt.getch()
            if ch2 == b"H":
                return "up"
            if ch2 == b"P":
                return "down"
            return None
        if ch in (b"h", b"H"):
            return "help"
        if ch in (b"q", b"Q"):
            return "quit"
        return None

elif _interactive:
    import termios
    import tty
    import select

    _original_termios = termios.tcgetattr(sys.stdin.fileno())
    tty.setcbreak(sys.stdin.fileno())

    def _restore_input():
        termios.tcsetattr(sys.stdin.fileno(), termios.TCSADRAIN, _original_termios)

    def _poll_key():
        ready, _, _ = select.select([sys.stdin], [], [], 0)
        if not ready:
            return None
        ch = sys.stdin.read(1)
        if ch == "\x1b":  # ESC - the start of an arrow-key escape sequence
            ready, _, _ = select.select([sys.stdin], [], [], 0.01)
            if not ready:
                return None
            ch2 = sys.stdin.read(1)
            if ch2 != "[":
                return None
            ready, _, _ = select.select([sys.stdin], [], [], 0.01)
            if not ready:
                return None
            ch3 = sys.stdin.read(1)
            if ch3 == "A":
                return "up"
            if ch3 == "B":
                return "down"
            return None
        if ch in ("h", "H"):
            return "help"
        if ch in ("q", "Q"):
            return "quit"
        return None

else:
    def _restore_input():
        pass

    def _poll_key():
        return None


def _print_help():
    cas_example_helper.print_version(APP_NAME, APP_VERSION)
    print("Keys: h = this help, q = quit, up/down = Analog Input 1 +/- 1.1")


# -----------------------------------------------------------------------------
# 4. main()
# -----------------------------------------------------------------------------
def main():
    global g_device_instance, g_bacnet_ip_udp_port, g_analog_input_1_value

    parser = ArgumentParser(prog="main.py", description=APP_NAME)
    parser.add_argument("--port", type=cas_example_helper.parse_port, default=47808,
                         metavar="<n>", help="BACnet/IP UDP port to listen on (default 47808)")
    parser.add_argument("--deviceID", type=cas_example_helper.parse_device_id, default=g_device_instance,
                         metavar="<inst>", help="BACnet Device instance (0..4194302, default 389001)")
    parser.add_argument("--version", action="store_true", help="Show version information and exit")
    args = parser.parse_args()

    g_device_instance = args.deviceID

    # --- Load the CAS BACnet Stack -------------------------------------------
    # Required before any other BACnetStack_* call, like the C++ edition's
    # LoadBACnetFunctions() - unlike the C# edition, where the .NET runtime
    # resolves the native library implicitly on the first P/Invoke call. If
    # this library lives next to main.py (the convention this example uses -
    # see README.md "Build the native CAS BACnet Stack library"), prefer that
    # copy over anything the OS's own library search path might find first.
    local_lib_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), libname)
    lib_path = local_lib_path if os.path.exists(local_lib_path) else libname
    try:
        library = ctypes.CDLL(lib_path)
    except OSError as ex:
        print(f"Error: failed to load the CAS BACnet Stack ({lib_path}): {ex}", file=sys.stderr)
        print("Copy CASBACnetStack_x64_Release.dll (Windows) / "
              "libCASBACnetStack_x64_Release.so (Linux) next to main.py - "
              "see README.md \"Build the native CAS BACnet Stack library\".", file=sys.stderr)
        return 1
    bacnet.bind(library)

    if args.version:
        cas_example_helper.print_version(APP_NAME, APP_VERSION)
        return 0

    cas_example_helper.print_version(APP_NAME, APP_VERSION)

    # --- Bind the BACnet/IP socket -------------------------------------------
    try:
        udp.setup(args.port)
    except OSError as ex:
        print(f"Error: could not bind UDP port {args.port}: {ex}", file=sys.stderr)
        print("Is another BACnet device already running on this machine? Try --port.", file=sys.stderr)
        return 1

    # Capture the BACnet/IP addressing the Network Port object will report.
    g_bacnet_ip_udp_port = args.port
    local = cas_example_helper.get_local_ipv4()
    for i, part in enumerate(local.address.split(".")):
        g_ip_address[i] = int(part)
    for i, part in enumerate(local.netmask.split(".")):
        g_ip_subnet_mask[i] = int(part)
    print(f"FYI: listening on {local.address}:{g_bacnet_ip_udp_port} "
          f"(broadcast {local.broadcast})")

    # --- Register callbacks ---------------------------------------------------
    # The transport + time callbacks are shared boilerplate, keyed to the
    # Network Port instance this socket will become.
    cas_example_helper.register_common_callbacks(udp, NETWORK_PORT_INSTANCE)

    # The property callbacks are specific to this example. Wrap each Python
    # function in the matching ctypes.CFUNCTYPE and keep the wrapper object
    # alive for the life of the process - see cas_example_helper.py's
    # "CALLBACKS MUST BE ROOTED" note; the same rule applies here.
    get_property_real_cb = bacnet.FPCallbackGetPropertyReal(get_property_real)
    get_property_enumerated_cb = bacnet.FPCallbackGetPropertyEnumerated(get_property_enumerated)
    get_property_unsigned_integer_cb = bacnet.FPCallbackGetPropertyUnsignedInteger(get_property_unsigned_integer)
    get_property_character_string_cb = bacnet.FPCallbackGetPropertyCharacterString(get_property_character_string)
    get_property_bool_cb = bacnet.FPCallbackGetPropertyBool(get_property_bool)
    get_property_octet_string_cb = bacnet.FPCallbackGetPropertyOctetString(get_property_octet_string)
    cas_example_helper._callback_refs.extend([
        get_property_real_cb, get_property_enumerated_cb, get_property_unsigned_integer_cb,
        get_property_character_string_cb, get_property_bool_cb, get_property_octet_string_cb,
    ])

    bacnet.BACnetStack_RegisterCallbackGetPropertyReal(get_property_real_cb)
    bacnet.BACnetStack_RegisterCallbackGetPropertyEnumerated(get_property_enumerated_cb)
    bacnet.BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(get_property_unsigned_integer_cb)
    bacnet.BACnetStack_RegisterCallbackGetPropertyCharacterString(get_property_character_string_cb)
    bacnet.BACnetStack_RegisterCallbackGetPropertyBool(get_property_bool_cb)
    bacnet.BACnetStack_RegisterCallbackGetPropertyOctetString(get_property_octet_string_cb)

    # --- Create the device -----------------------------------------------------
    if not bacnet.BACnetStack_AddDevice(g_device_instance):
        print(f"Error: Failed to add the Device {g_device_instance}.")
        return 1

    # Enable ReadProperty (DS-RP-B) - the one mandatory service for B-SS.
    # We set it explicitly to make the profile requirement obvious.
    #
    # We deliberately do NOT enable WriteProperty, ReadPropertyMultiple,
    # SubscribeCOV, or any alarm/event service: a Smart Sensor does not
    # require them, so a faithful B-SS example leaves them off.
    if not bacnet.BACnetStack_SetServiceEnabled(g_device_instance, c.SERVICE_READ_PROPERTY, True):
        print("Error: Failed to enable the ReadProperty service.")
        return 1

    # Discovery: Who-Is/I-Am (DM-DDB-B) and Who-Has/I-Have (DM-DOB-B).
    #
    # These need enabling even though the device already ANSWERS them. The
    # stack's service defaults are whoIs + whoHas + readProperty only - iAm
    # and iHave are left False. Who-Is is answered and the start-up I-Am is
    # sent regardless, because neither is gated on the bit; but
    # Protocol_Services_Supported is emitted verbatim from that bitstring, so
    # without these calls the device DOES I-Am and I-Have while telling every
    # client it supports neither. The README claims DM-DDB-B and DM-DOB-B;
    # this is what makes the claim true on the wire.
    if not (bacnet.BACnetStack_SetServiceEnabled(g_device_instance, c.SERVICE_WHO_IS, True) and
            bacnet.BACnetStack_SetServiceEnabled(g_device_instance, c.SERVICE_I_AM, True) and
            bacnet.BACnetStack_SetServiceEnabled(g_device_instance, c.SERVICE_WHO_HAS, True) and
            bacnet.BACnetStack_SetServiceEnabled(g_device_instance, c.SERVICE_I_HAVE, True)):
        print("Error: Failed to enable the discovery services (Who-Is/I-Am, Who-Has/I-Have).")
        return 1

    # --- Add the read-only sensor objects ---------------------------------------
    if not bacnet.BACnetStack_AddObject(g_device_instance, c.OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE):
        print(f"Error: Failed to add Analog Input {ANALOG_INPUT_INSTANCE} (Bronze).")
        return 1
    if not bacnet.BACnetStack_AddObject(g_device_instance, c.OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE):
        print(f"Error: Failed to add Binary Input {BINARY_INPUT_INSTANCE} (Emerald).")
        return 1
    if not bacnet.BACnetStack_AddObject(g_device_instance, c.OBJECT_TYPE_MULTI_STATE_INPUT,
                                         MULTI_STATE_INPUT_INSTANCE):
        print(f"Error: Failed to add Multi-State Input {MULTI_STATE_INPUT_INSTANCE} (Hot Pink).")
        return 1

    # --- Add the Network Port object --------------------------------------------
    # Every BACnet device (Protocol_Revision 17+) must have at least one
    # Network Port object describing the port it talks on. This one is the
    # BACnet/IP application port; it is the lowest layer, so its reference
    # port is "none". networkNumber 0 with quality "unknown" describes a
    # local port that has not learned its network number - the right answer
    # for a device that is not a router and has not been told one.
    if not bacnet.BACnetStack_AddNetworkPortObject(
            g_device_instance, NETWORK_PORT_INSTANCE,
            c.NETWORK_PORT_NETWORK_TYPE_IPV4,
            c.NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
            0,  # networkNumber: not configured
            c.NETWORK_NUMBER_QUALITY_UNKNOWN,
            c.NETWORK_PORT_REFERENCE_PORT_NONE):
        print("Error: Failed to add Network Port 1 (Vermilion).")
        return 1

    # --- Enable the OPTIONAL properties we choose to expose ---------------------
    # The stack automatically enables an object's REQUIRED properties when the
    # object is added (AddObject / AddNetworkPortObject) - so Units, Polarity,
    # Number_Of_States, Out_Of_Service, and the Network Port's BACnet/IP
    # addressing (IP_Address, IP_Subnet_Mask, BACnet_IP_UDP_Port, ...) are
    # already enabled; our Get* callbacks just supply their values. Only
    # OPTIONAL properties need SetPropertyEnabled. State_Text is optional on a
    # Multi-State Input, so we enable it here (and serve it in
    # get_property_character_string).
    #
    # The Device's Description is optional too, and it is an easy one to get
    # wrong: serving it from a Get callback is NOT enough. The stack checks
    # IsPropertyEnabled BEFORE it ever reaches the callbacks, and for an
    # optional property that check falls back to "is it required?" - which is
    # False. So a Description branch in the callback without this enable is
    # DEAD CODE, and the client reads back Error: unknown-property.
    if not bacnet.BACnetStack_SetPropertyEnabled(g_device_instance, c.OBJECT_TYPE_DEVICE,
                                                  g_device_instance, c.PROPERTY_IDENTIFIER_DESCRIPTION, True):
        print("Error: Failed to enable Description on the Device object.")
        return 1
    if not bacnet.BACnetStack_SetPropertyEnabled(g_device_instance, c.OBJECT_TYPE_MULTI_STATE_INPUT,
                                                  MULTI_STATE_INPUT_INSTANCE,
                                                  c.PROPERTY_IDENTIFIER_STATE_TEXT, True):
        print("Error: Failed to enable State_Text on Multi-State Input 1 (Hot Pink).")
        return 1

    # Who-Is is answered automatically. The spec also requires a device to
    # announce itself on start-up, so broadcast an unsolicited I-Am now (to
    # the local subnet broadcast - the Network Port's own network).
    if not cas_example_helper.send_i_am(g_device_instance, g_bacnet_ip_udp_port, NETWORK_PORT_INSTANCE):
        print("Error: SendIAm failed.")
        return 1

    print(f"FYI: Device {g_device_instance} (\"{DEVICE_NAME}\") ready. "
          f"Vendor ID {VENDOR_IDENTIFIER}. Press 'h' for help.")

    # --- Graceful Ctrl+C shutdown ------------------------------------------------
    running = {"value": True}

    def _on_sigint(signum, frame):
        running["value"] = False  # handle it ourselves instead of the process dying mid-tick

    signal.signal(signal.SIGINT, _on_sigint)
    if hasattr(signal, "SIGTERM"):
        signal.signal(signal.SIGTERM, _on_sigint)

    # --- Run the stack -------------------------------------------------------------
    # BACnetStack_Tick() processes incoming messages and timers. Call it
    # continuously, and poll the keyboard for interactive commands. The stack
    # is single-threaded by contract - everything below runs in this one loop,
    # with no worker thread touching the stack or the socket.
    try:
        while running["value"]:
            bacnet.BACnetStack_Tick()

            key = _poll_key()
            if key == "help":
                _print_help()
            elif key == "quit":
                running["value"] = False
            elif key == "up":
                g_analog_input_1_value += 1.1
                print(f"Analog Input 1 (Bronze) = {g_analog_input_1_value:.1f} C")
            elif key == "down":
                g_analog_input_1_value -= 1.1
                print(f"Analog Input 1 (Bronze) = {g_analog_input_1_value:.1f} C")

            time.sleep(0.001)  # 1 ms - be a good citizen, don't spin the CPU
    finally:
        _restore_input()
        udp.shutdown()

    print("FYI: stopped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
